/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "test",
      "frontmatter": {
        "title": "test",
        "date": "2020-05-29T00:00:00.000Z"
      },
      "regularPath": "/theme-reco/",
      "relativePath": "theme-reco/README.md",
      "key": "v-e445b00e",
      "path": "/theme-reco/"
    },
    {
      "title": "plugin",
      "frontmatter": {
        "title": "plugin",
        "date": "2020-05-28T00:00:00.000Z"
      },
      "regularPath": "/theme-reco/plugin.html",
      "relativePath": "theme-reco/plugin.md",
      "key": "v-47ba4132",
      "path": "/theme-reco/plugin.html"
    },
    {
      "title": "api",
      "frontmatter": {
        "title": "api",
        "date": "2020-05-29T00:00:00.000Z"
      },
      "regularPath": "/theme-reco/api.html",
      "relativePath": "theme-reco/api.md",
      "key": "v-25e5b222",
      "path": "/theme-reco/api.html"
    },
    {
      "title": "test",
      "frontmatter": {
        "title": "test",
        "date": "2020-05-27T00:00:00.000Z"
      },
      "regularPath": "/theme-reco/theme.html",
      "relativePath": "theme-reco/theme.md",
      "key": "v-47a488f8",
      "path": "/theme-reco/theme.html"
    }
  ],
  "themeConfig": {}
}